apiVersion: apps/v1
kind: Deployment
metadata:
  name: maven-app
  labels:
    app: maven-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maven-app
  template:
    metadata:
      labels:
        app: maven-app
    spec:
      containers:
      - name: maven-app
        image: mdabrar4devops/maven_app:${BUILD_NUMBER}
        imagePullPolicy: Always                                                         
        resources:
          limits:
            cpu: "2"
            memory: "2048Mi"
          requests:
            cpu: "0.2"
            memory: "1024Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 3
        ports:
        - containerPort: 3000
    
---

apiVersion: v1
kind: Service
metadata:
  name: maven-app
  namespace: apps
spec:
  selector:
    app: maven-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
    - protocol: TCP
      port: 443
      targetPort: 8080
      name: https
