apiVersion: apps/v1
kind: Deployment
metadata:
  name: maven-app
  labels:
    app: maven-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maven-app
  template:
    metadata:
      labels:
        app: maven-app
    spec:
      containers:
      - name: maven-app
        image: mdabrar4devops/onlinebookstore:$BUILD_NUMBER
        imagePullPolicy: Always                                                         
        resources:
          limits:
            cpu: "2"
            memory: "2048Mi"
          requests:
            cpu: "0.2"
            memory: "1024Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 30002
          initialDelaySeconds: 300
          periodSeconds: 300
        ports:
        - containerPort: 8080
    
---

apiVersion: v1
kind: Service
metadata:
  name: maven-app
spec:
  type: NodePort
  selector:
    app: maven-app
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30002
      name: http


'''
apiVersion: v1
kind: Service
metadata:
  name: maven-app
spec:
  type: ClusterIP
  selector:
    app: maven-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      name: http
'''
